version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: clielink_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: clielinkdb
      MYSQL_USER: clielink_user
      MYSQL_PASSWORD: clielink_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: clielink_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"

volumes:
  mysql_data:
